### ISSUE TITLE
Is replikativ designed to succeed?

### ISSUE THREAD

**Issue by aschrijver** [replikativ/replikativ#8]
Yep, a clickbait title :smile: 

I really like the problems that replikativ is trying to solve! That _rocks_!! :fist_oncoming: 
This initiative deserves to prosper. But I fear this is really hard given your size and positioning.

I just created a discussion piece in your 'competitor's' project issue tracker that explains my points:
[Is dat designed to be unfindable in Google?](https://github.com/datproject/dat/issues/824)

Did you ever consider of joining forces with the dat project?

Wonderful work, keep it up guys and girls!

**Comment by aschrijver** [comment]
I'm sorry but it seems most of the discussion is on the Dat issue tracker. But please join in.

PS I am in no way or form affiliated with Dat. Just bumped into both your technologies and had some questions and suggestions..

**Comment by whilo** [comment]
I am very open to cooperation, but people from the dat project have so far not shown any interest (in the chats). Having some general discussion can be good, but it would be important in my opinion to focus on a particular issue. If you can help build a bridge, then I am very happy to discuss.

**Comment by aschrijver** [comment]
Thanks. I am trying. I just added another long - but I think very interesting - contribution to the discussion: https://github.com/datproject/dat/issues/824#issuecomment-315740501 and get positive feedback so far.

Why don't you introduce yourself and your interest on that same Dat discussion thread?

PS I find the #dat freenode is more for ad-hoc questions. I just posted a clickbait, but no one is there (and with freenode you don't see history when you login, like in Gitter)

**Comment by aschrijver** [comment]
FYI I have now cleaned and tailored the discussion specifically to Dat. It can be found here: https://github.com/datproject/discussions/issues/58

Based on it Dat has decided it is useful to have an event-based abstraction layer on top of hypercore.
